language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
#    global:
#        - PLATFORMIO_BUILD_FLAGS=-Werror
    matrix:
        - PLATFORMIO_CI_SRC=SodaqOneTracker PLATFORMIO_CI_EXTRA_ARGS="--board=sodaq_one"

install:
    - pip install -U platformio
    - pio update

script:
    - platformio ci $PLATFORMIO_CI_EXTRA_ARGS
